### ISSUE TITLE
The Phoenix Project

### ISSUE THREAD

**Issue by NoahJaehnert** [jacobian/infosec-engineering#1]
While not directly relevant to InfoSec Engineering, the lessons learned about work, processes, and IT Operations in The Phoenix Project have been invaluable to me. I'd highly suggest it: 

http://amzn.com/0988262509
http://itrevolution.com/books/phoenix-project-devops-book/
https://en.wikipedia.org/wiki/The_Phoenix_Project_(novel)

**Comment by jacobian** [comment]
Thanks for the suggestion, it was an interesting read. There was some good stuff in there, but the rather blatant sexism made it pretty hard to take seriously, and definitely makes it something I'm not comfortable recommending.
