### ISSUE TITLE
Yubikey Handbook

### ISSUE THREAD

**Issue by ruimarinho** [jacobian/infosec-engineering#3]
Suggesting a reference to an ebook I've recently released on Yubikeys.

> Yubikey is an hardware device manufactured by Yubico that provides several forms of strong authentication and encryption. It has many use cases and interesting applications.

> The Yubikey Handbook is an attempt of exploring those use cases and is intended to be a living document. It is focused on the Yubikey 4/Yubikey 4 Nano. With some adaptations, parts of this document will also apply to the Yubikey NEO.

https://github.com/ruimarinho/yubikey-handbook

**Comment by jacobian** [comment]
Thanks for the pointer! I was just about a week ago wishing that someone would write a "all the things you can do with your yubikey" document, and bam, here this is. Awesome!

I do think this is a bit too special-purpose for what I'm trying to collect here in this reading list, but I'm super-excited to know about this book. Thank you again for pointing it out!

**Comment by ruimarinho** [comment]
Thank you! I'm glad you find it useful too. It's an open book so if you find anything missing there, an issue or PR is welcomed! :)

I also appreciate the time you've invested curating this list - it is full of awesome content!
