### ISSUE TITLE
Suggesting a couple of books that you might want to check out

### ISSUE THREAD

**Issue by sparcflow** [jacobian/infosec-engineering#7]
Hey,
If you would like to check out a couple of books that take on a different approach to hacking, hopefully it will be worth your time ;)
How to hack Like a pornstar - https://books2read.com/u/bWzdBx
How to hack like a legend (for more experienced folks) - https://amzn.to/2uWh1Up

The approach is unique. The reader shadows a hacker while breaking into a company. They get to see the complete security chain from preparing the payload to actually hacking a Mainframe or evading the latest "next-gen" product.
Would love your feedback ;)

Cheers,

**Comment by jacobian** [comment]
That title makes it something I'm not going to be comfortable recommending, regardless of the quality. It's not appropriate for a professional setting, and my aim is to make this a resource for security professionals. Thanks for the recs, but I'll pass.
